pipeline:
  lint:
    image: python:3.8-slim
    pull: true
    commands:
      - pip install flake8
      - flake8
  publish:
    image: plugins/ecr
    pull: true
    settings:
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key
      repo: gn-api-me
      registry: 483957310387.dkr.ecr.ap-southeast-1.amazonaws.com
      region: ap-southeast-1
      dockerfile: Dockerfile
      tags:
        - latest