pipeline:
  lint:
    image: python:3.8-slim
    pull: true
    commands:
      - pip install flake8
      - flake8
  publish:
    image: plugins/ecr
    settings:
      access_key: ecr_access_key
      secret_key: ecr_secret_key
      repo: gn-api-me
      registry: ecr_registry
      region: ap-southeast-1
      tags: latest