pipeline:
  lint:
    image: python:3.8-slim
    pull: true
    commands:
      - pip install flake8
      - flake8
  ecr-auth:
    image: omerxx/drone-ecr-auth
    pull: true
    privileged: true
    environment:
      - AWS_ACCESS_KEY_ID=$ecr_access_key
      - AWS_SECRET_ACCESS_KEY=$ecr_secret_key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - $(aws ecr get-login-password --region ap-southeast-1)
      - docker login --username AWS --password-stdin 483957310387.dkr.ecr.ap-southeast-1.amazonaws.com
      - docker build -t gn-api-me .
      - docker tag gn-api-me:latest 483957310387.dkr.ecr.ap-southeast-1.amazonaws.com/gn-api-me:$$DRONE_BUILD_NUMBER
      - docker push 483957310387.dkr.ecr.ap-southeast-1.amazonaws.com/gn-api-me:$$DRONE_BUILD_NUMBER
      - docker push 483957310387.dkr.ecr.ap-southeast-1.amazonaws.com/gn-api-me:latest
      - docker rmi 483957310387.dkr.ecr.ap-southeast-1.amazonaws.com/gn-rails:$$DRONE_BUILD_NUMBER
