version: '2'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
      image: postgres:9.5-alpine
      volumes:
        - dbvolumn02:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - '5433:5432'
volumes:
  dbvolumn02:
    external:
      name: goodnight-rails_dbvolumn02