version: '2'
services:
  api:
    restart: always
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data